# Basic
title: Francesca M. Cassola
subtitle: Behavioural Ecologist and Science Communicator
welcome_message: From behaviour to conservation, with a passion for storytelling.
description: MSCA Postdoctoral Research Fellow at Anglia Ruskin University, Cambridge, Uk
creator: Francesca M. Cassola

url: "https://tuo_username.github.io/tuo_repo"

permalink: /:year/:month/:title/
highlighter: rouge
cover_color: red

# Blog button
blog_button:
  title: Blog
  description: Updates and reflections from my work

# Main navigation
nav:
  - {title: CV, description: Education and publications, url: '/cv'}
  - {title: Drops of Science, description: Podcast and public outreach, url: '/science-outreach'}
  - {title: EvOCRO, description: My current MSCA project, url: '/project'}
  - {title: Blog, description: Updates and thoughts, url: '/blog'}
  - {title: IT 🇮🇹, description: Versione italiana, url: '/it/'}
  - {title: ES 🇪🇸, description: Versión en español, url: '/es/'}

# Social
social:
  linkedin: https://www.linkedin.com/in/francescamauracassola/
  twitter: https://x.com/xisca_cassola
  bluesky: https://bsky.app/profile/xiscacassola.bsky.social
  orcid: https://orcid.org/0000-0002-0849-0070
  podcast: https://open.spotify.com/show/tuo-podcast

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comments (off)
comment:
  disqus: ''

# Google Analytics (optional)
ga:
  # id: UA-xxxxxxxx
  # host: tuo_sito
