# Basic
title: Francesca M. Cassola
subtitle: Behavioural Ecologist and Science Communicator
welcome_message: Welcome, friend!
description: Personal website of Francesca M. Cassola – Marie Curie Fellow at ARU
creator: Francesca M. Cassola

url: "https://tuo_username.github.io/tuo_repo"

permalink: /:year/:month/:title/
highlighter: rouge
cover_color: slate

# Blog button
blog_button:
  title: Blog
  description: Thoughts, updates and science

# Main navigation
nav:
  - {title: CV, description: Academic Curriculum, url: '/cv'}
  - {title: Science Outreach, description: Podcast and more, url: '/science-outreach'}
  - {title: University, description: Anglia Ruskin University, url: 'https://aru.ac.uk'}
  - {title: Project, description: EvOCRO project, url: '/project'}
  - {title: IT 🇮🇹, description: Versione italiana, url: '/it/'}
  - {title: ES 🇪🇸, description: Versión en español, url: '/es/'}

# Social
social:
  github: francesca-cassola
  linkedin: francesca-cassola
  twitter: cassolafranci
  mail: francesca.cassola@email.com
  podcast: https://open.spotify.com/show/tuo-podcast

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comments (off)
comment:
  disqus: ''

# Google Analytics (optional)
ga:
  # id: UA-xxxxxxxx
  # host: tuo_sito
